# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: postgres:14.0
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB_PORT: "5432"
      POSTGRES_DB_HOST: "localhost"
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      # PGDATA: /var/lib/postgresql/data/pgdata
      PGDATA: /tmp
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/pgdata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data:
    # driver: local

